### ISSUE TITLE
既にホワイトリストにあってトグルボタンで変えたやつは焼けてない by satomi

### ISSUE THREAD

**Issue by daicche** [daicche/quiche_issues#1]
> satomi [12:34 PM] 
> 私も、既にホワイトリストにあってトグルボタンで変えたやつは焼けてない気がする
> [12:35] 
> Add this Websiteの場合は大丈夫なのだけど

原因を調査する

**Comment by daicche** [comment]
http://headlines.yahoo.co.jp/ted?a=20160209-00002357-ted
こういうページだと、 `http://headlines.yahoo.co.jp/ted` で投稿されてしまうので、
canonical_url が設定されていなければ、 `og:url` をまず見るようにする

**Comment by sattomi** [comment]
既にホワイトリストにあって、allowしていないはずのものも、quicheのアイコン自体は灰色なのに、毎回allow this site? がyesに表示される。
yesとnoを切り替えた瞬間は正しく反映されるが、もう一度アイコンを押して開くと、yesに戻っている。アイコンの色は灰色のまま。

![screen shot 2016-05-19 at 3 23 33 pm](https://cloud.githubusercontent.com/assets/4344192/15384519/31563a30-1dd6-11e6-86d1-775f80a2a6d1.png)

**Comment by daicche** [comment]
直しました 🙇
