### ISSUE TITLE
chrome storeからのインストール時メッセージが怖い

### ISSUE THREAD

**Issue by yrhorita** [daicche/quiche_issues#12]
> 次の権限にアクセス可能:
> アクセスしたウェブサイト上にある自分の全データの読み取りと変更

if possible!

**Comment by daicche** [comment]
無理そうだった 🙇

**Comment by daicche** [comment]
有名どころだと
- AdBlock
- AdBlock Plus
- AutoPatchWork
- Awesome Screenshot
- Evernote Web Clipper
- Hatena Bookmark
- Pushbullet
- Save to Pocket

も同様の権限が必要とのこと
