### ISSUE TITLE
自分の名前出ない

### ISSUE THREAD

**Issue by yrhorita** [daicche/quiche_issues#13]
仕様？
<img width="821" alt="2016-02-08 12 09 18" src="https://cloud.githubusercontent.com/assets/2705670/12877813/e0430e34-ce5c-11e5-95eb-6d0a0d6675f6.png">

**Comment by yrhorita** [comment]
こんなのもあった
<img width="1175" alt="2016-02-08 12 19 51" src="https://cloud.githubusercontent.com/assets/2705670/12877910/5110cdda-ce5e-11e5-9670-c954c2ec2b68.png">

**Comment by daicche** [comment]
他のチームの人が読んでいる時に出るバグです :scream: 
直します…！ ありがとう！！
