### ISSUE TITLE
websiteの提案ができる機能

### ISSUE THREAD

**Issue by koharashota** [daicche/quiche_issues#15]
新しいサイトの追加提案とかできたら

**Comment by daicche** [comment]
今は誰でも追加できるようになってるんだけど、
逆に溢れかえって制御不能な感じある汗
<img width="422" alt="2016-02-09 at 13 44 10" src="https://cloud.githubusercontent.com/assets/823185/12907824/4134d75a-cf33-11e5-9d42-43130a8b527b.png">

今後はカテゴリー分けとか推薦ウェブサイトとか作っていきたい

**Comment by daicche** [comment]
あと、ウェブサイト追加しても他の人に知られるような仕組みがまだ無い :scream:

**Comment by koharashota** [comment]
おー、気づいてなかった！
