### ISSUE TITLE
読んでいる人がいるはずなのに、誰が読んでいるか表示されない場合がある

### ISSUE THREAD

**Issue by sattomi** [daicche/quiche_issues#23]
どういう条件でこうなるのかは不明

![screen shot 2016-04-14 at 2 18 20 pm](https://cloud.githubusercontent.com/assets/4344192/14532542/5388fa2a-029c-11e6-89b3-481695756faa.png)

**Comment by daicche** [comment]
canonical_url が適切に取れてないパターンかな…
