### ISSUE TITLE
Readingsのデザイン

### ISSUE THREAD

**Issue by sattomi** [daicche/quiche_issues#25]
全体的にもう少しメリハリのあるデザインだと見やすいかなと思いました
- titleの文字のfont-sizeを上げる
- Commentを鉛筆マークとかのアイコンに
- Destroyもゴミ箱とかのアイコンに
- 日付はカラムの要素ではなく、slackとかみたいに、仕切りの形で
- アイコンの横の名前は人数によってはなくてもいいかも…？
- 記事のサムネイルがあったら嬉しい(記事の中に画像がある場合のみとか)

**Comment by daicche** [comment]
ありがとう 🙇

**Comment by daicche** [comment]
- [x] titleの文字のfont-sizeを上げる
- [x] Commentを鉛筆マークとかのアイコンに
- [x] Destroyもゴミ箱とかのアイコンに
- [ ] 日付はカラムの要素ではなく、slackとかみたいに、仕切りの形で
- [x] アイコンの横の名前は人数によってはなくてもいいかも…？
- [x] 記事のサムネイルがあったら嬉しい(記事の中に画像がある場合のみとか)
