### ISSUE TITLE
登録していないウェブサイトの記事でも意図的に投稿できるようにする

### ISSUE THREAD

**Issue by daicche** [daicche/quiche_issues#27]

**Comment by sattomi** [comment]
これは、そのサイトを追加せずに、そのページだけイレギュラーに焼くってこと??
凄く欲しいけど、そうしたらそれは誰が見られるようになるの？ホワイトリストでそこのドメイン追加している人？

**Comment by daicche** [comment]
> そのサイトを追加せずに、そのページだけイレギュラーに焼くってこと??

ですです。

> 誰が見られるようになるの？

属するチーム内の全ての人を想定してたけど、よくなさそう…？

**Comment by sattomi** [comment]
なるほど！
それが一番いいと思います！
